# fly.toml app configuration file generated for my-ph-fso on 2023-05-28T16:35:34+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-ph-fso"
primary_region = "sin"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
